name: user_auth_try7
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth:
  cloud_firestore: ^4.14.0
  flutter_gemini: ^2.0.5
  image_picker: ^1.1.2
  google_fonts:
  flutter_launcher_icons: ^0.13.1
  http: ^1.2.2
  intl: ^0.17.0
  fluttertoast:
  speech_to_text:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: CinzelDecorative
      fonts:
        - asset: assets/fonts/CinzelDecorative-Regular.ttf


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
