// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXgP0kM2898AcFflPMkpitVUvZVSaZSN0',
    appId: '1:631795401642:web:your-web-app-id',
    messagingSenderId: '631795401642',
    projectId: 'test7-a139a-6e200',
    authDomain: 'test7-a139a-6e200.firebaseapp.com',
    storageBucket: 'test7-a139a-6e200.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXgP0kM2898AcFflPMkpitVUvZVSaZSN0',
    appId: '1:631795401642:android:1ec1960630f7529043e1d3',
    messagingSenderId: '631795401642',
    projectId: 'test7-a139a-6e200',
    storageBucket: 'test7-a139a-6e200.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Y3knHP4jvmT76WlwJu7VeRxN9bRNYjc',
    appId: '1:631795401642:ios:your-ios-app-id',
    messagingSenderId: '631795401642',
    projectId: 'test7-a139a-6e200',
    storageBucket: 'test7-a139a-6e200.appspot.com',
    iosBundleId: 'com.example.user_auth_try7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2Y3knHP4jvmT76WlwJu7VeRxN9bRNYjc',
    appId: '1:631795401642:ios:your-ios-app-id',
    messagingSenderId: '631795401642',
    projectId: 'test7-a139a-6e200',
    storageBucket: 'test7-a139a-6e200.appspot.com',
    iosBundleId: 'com.example.user_auth_try7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXgP0kM2898AcFflPMkpitVUvZVSaZSN0',
    appId: '1:631795401642:web:your-windows-app-id',
    messagingSenderId: '631795401642',
    projectId: 'test7-a139a-6e200',
    authDomain: 'test7-a139a-6e200.firebaseapp.com',
    storageBucket: 'test7-a139a-6e200.appspot.com',
  );
}
